# Generated by Django 4.2.3 on 2023-07-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('favoritefood', models.CharField(max_length=50)),
                ('favoritetoy', models.CharField(max_length=50)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_app.breed')),
            ],
        ),
    ]
